import { useEffect, useRef, useState } from "react";
import { useAuthStore } from "../state/authStore";
import { uploadAvatar, deleteAvatar, resolveAvatarUrl } from "../lib/api";
import { validateGlbFile } from "../lib/glbValidation";
import { RealisticAvatarPreview } from "./RealisticAvatarPreview";

interface AvatarUploadProps {
  onClose: () => void;
}

type Stage =
  | { kind: "idle" }
  | { kind: "staged"; file: File; previewUrl: string }
  | { kind: "uploading"; file: File; previewUrl: string; progress: number }
  | { kind: "error"; message: string };

/**
 * Create/Upload → Validate → Preview → Save → (used automatically on room entry). Lets a user
 * attach a realistic rigged avatar (GLB) generated by an external tool — see README "Realistic
 * avatars" for why this app doesn't run avatar generation itself. Any tool that exports a
 * standard humanoid-rigged GLB with ARKit-named blendshapes works; nothing here is tied to one
 * vendor's output.
 */
export function AvatarUpload({ onClose }: AvatarUploadProps) {
  const token = useAuthStore((s) => s.token);
  const profile = useAuthStore((s) => s.profile);
  const updateProfile = useAuthStore((s) => s.updateProfile);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [stage, setStage] = useState<Stage>({ kind: "idle" });
  const [dragActive, setDragActive] = useState(false);
  const [deleteBusy, setDeleteBusy] = useState(false);

  // Revoke the object URL whenever we leave a staged/uploading state pointing at one, so we
  // don't leak blob URLs across repeated selections.
  useEffect(() => {
    return () => {
      if (stage.kind === "staged" || stage.kind === "uploading") URL.revokeObjectURL(stage.previewUrl);
    };
  }, [stage]);

  const stageFile = async (file: File) => {
    const result = await validateGlbFile(file);
    if (!result.ok) {
      setStage({ kind: "error", message: result.error! });
      return;
    }
    setStage({ kind: "staged", file, previewUrl: URL.createObjectURL(file) });
  };

  const cancelStaged = () => {
    if (stage.kind === "staged") URL.revokeObjectURL(stage.previewUrl);
    setStage({ kind: "idle" });
  };

  const save = async () => {
    if (stage.kind !== "staged" || !token) return;
    const { file, previewUrl } = stage;
    setStage({ kind: "uploading", file, previewUrl, progress: 0 });
    try {
      const { profile: updated } = await uploadAvatar(token, file, (fraction) =>
        setStage((prev) => (prev.kind === "uploading" ? { ...prev, progress: fraction } : prev))
      );
      updateProfile(updated);
      URL.revokeObjectURL(previewUrl);
      setStage({ kind: "idle" });
    } catch (err) {
      setStage({ kind: "error", message: err instanceof Error ? err.message : "Upload failed" });
    }
  };

  const handleDelete = async () => {
    if (!token) return;
    setDeleteBusy(true);
    try {
      const { profile: updated } = await deleteAvatar(token);
      updateProfile(updated);
    } catch (err) {
      setStage({ kind: "error", message: err instanceof Error ? err.message : "Delete failed" });
    } finally {
      setDeleteBusy(false);
    }
  };

  const onDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragActive(false);
    const file = e.dataTransfer.files?.[0];
    if (file) void stageFile(file);
  };

  const errorMessage = stage.kind === "error" ? stage.message : null;
  const isStagedOrUploading = stage.kind === "staged" || stage.kind === "uploading";

  return (
    <div className="avatar-upload-overlay">
      <div className="avatar-upload-panel">
        <h2>Realistic avatar</h2>
        <p className="avatar-upload__body">
          Create a realistic rigged avatar of yourself with a free tool, then upload the exported{" "}
          <strong>.glb</strong> file here. It replaces the stylized default avatar with one that
          actually looks like you — your camera still drives it in real time the same way. It's
          used automatically whenever you enter a room.
        </p>
        <ul className="avatar-upload__tools">
          <li>
            <a href="https://avaturn.me" target="_blank" rel="noreferrer">
              Avaturn
            </a>{" "}
            — free, photo-based, exports GLB with ARKit blendshapes
          </li>
          <li>
            <a href="https://avatarsdk.com/avatar-creator/" target="_blank" rel="noreferrer">
              Avatar SDK
            </a>{" "}
            — free selfie-to-avatar, full body
          </li>
        </ul>
        <p className="avatar-upload__hint">
          Nothing about your photo touches our servers during creation — that happens entirely on
          the external tool's site. We only ever receive the finished 3D file you choose to
          upload.
        </p>

        <input
          ref={fileInputRef}
          type="file"
          accept=".glb"
          style={{ display: "none" }}
          onChange={(e) => {
            const file = e.target.files?.[0];
            e.target.value = ""; // allow re-selecting the same filename later
            if (file) void stageFile(file);
          }}
        />

        {isStagedOrUploading ? (
          <>
            <p className="avatar-upload__current">Preview — not saved yet</p>
            <RealisticAvatarPreview url={stage.previewUrl} key={stage.previewUrl} />
            {stage.kind === "uploading" && (
              <div className="upload-progress">
                <div className="upload-progress__track">
                  <div className="upload-progress__fill" style={{ width: `${Math.round(stage.progress * 100)}%` }} />
                </div>
                <span className="upload-progress__label">Uploading… {Math.round(stage.progress * 100)}%</span>
              </div>
            )}
            <div className="lobby__card">
              <button disabled={stage.kind === "uploading"} onClick={save}>
                {stage.kind === "uploading" ? "Uploading…" : "Save avatar"}
              </button>
              <button disabled={stage.kind === "uploading"} onClick={cancelStaged}>
                Cancel
              </button>
            </div>
          </>
        ) : (
          <>
            {profile?.avatarUrl && (
              <>
                <p className="avatar-upload__current">✓ Realistic avatar active</p>
                <RealisticAvatarPreview url={resolveAvatarUrl(profile.avatarUrl)} />
              </>
            )}

            <div
              className={`avatar-dropzone${dragActive ? " avatar-dropzone--active" : ""}`}
              onDragOver={(e) => {
                e.preventDefault();
                setDragActive(true);
              }}
              onDragLeave={() => setDragActive(false)}
              onDrop={onDrop}
              onClick={() => fileInputRef.current?.click()}
            >
              {dragActive ? "Drop the .glb file here" : "Drag & drop a .glb file here, or click to choose one"}
            </div>

            {profile?.avatarUrl && (
              <div className="lobby__card">
                <button disabled={deleteBusy} onClick={handleDelete}>
                  {deleteBusy ? "Removing…" : "Remove avatar"}
                </button>
              </div>
            )}
          </>
        )}

        {errorMessage && <p className="lobby__error">{errorMessage}</p>}

        <button className="link-button" onClick={onClose}>
          Close
        </button>
      </div>
    </div>
  );
}
